# This workflow checks if the project can be built correctly and runs its unit tests and linter
# After the tests have run it prints a report in the logs and uploads a report as workflow artifact
# This workflow only runs if a Pull Request is (re-)opened and it is not a draft
# or after a push to develop or the default branch
# For more information about best practices, see:
# https://grandcentrix.atlassian.net/wiki/spaces/TENG/pages/31180230199/GitHub+Actions+Best+Practices

name: Pull Request

on:
  push:
    branches: [ develop, main ]
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build all variants
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@750cdda3edd6d51b7fdfc069d2e2818cf3c44f4c #v3.3.1
      - name: Build all variants
        run: ./gradlew assemble
        env:
          GITHUB_PAT: ${{ secrets.PACKAGES_READ_TOKEN }}
        timeout-minutes: 10

  test:
    name: Run Unit Tests & Lint
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@750cdda3edd6d51b7fdfc069d2e2818cf3c44f4c #v3.3.1
      - name: Compile tests
        run: ./gradlew compileDebugUnitTests
        env:
          GITHUB_PAT: ${{ secrets.PACKAGES_READ_TOKEN }}
        timeout-minutes: 10
      - name: Run tests
        run: ./gradlew testDebugUnitTest --continue
        env:
          GITHUB_PAT: ${{ secrets.PACKAGES_READ_TOKEN }}
        continue-on-error: true
        timeout-minutes: 10
      - name: Run lint
        run: ./gradlew lintDebug
        continue-on-error: true
        timeout-minutes: 5
      - name: Annotate PR with JUnit Report
        uses: mikepenz/action-junit-report@9379f0ccddcab154835d4e2487555ee79614fe95 # v4.2.1
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Annotate PR with Lint Report
        uses: yutailang0119/action-android-lint@bd0b5a7d2cc453d16080b90e2a975d4af4aa9588 # v4.0.0
        with:
          report-path: app/build/reports/lint-results-debug.xml
      - name: Upload test and lint reports
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: reports
          path: "**/build/reports/*"